project_id = "qbcrkpgndedocghyvisv"

[functions.generate-material-metadata]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.check-duplicate-material]
verify_jwt = true

[functions.clerk-webhook]
verify_jwt = false